all:
	$(MAKE) release -C base64
	$(MAKE) release -C hex 
	$(MAKE) release -C rle
	$(MAKE) release -C synlfsr
	$(MAKE) release -C haffman
debug:
	$(MAKE) -C base64
	$(MAKE) -C hex 
	$(MAKE) -C rle
	$(MAKE) -C synlfsr
	$(MAKE) -C haffman
test:
	$(MAKE) test -C base64 
	$(MAKE) test -C hex 
	$(MAKE) test -C rle
	$(MAKE) test -C synlfsr
	$(MAKE) test -C haffman
clean:
	$(MAKE) clean -C base64
	$(MAKE) clean -C hex 
	$(MAKE) clean -C rle
	$(MAKE) clean -C synlfsr
	$(MAKE) clean -C haffman
